apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    location: AU
    creator: alex

spec:
  containers:
    - name: nginx-container
      image: nginx

    - name: backend-container
      image: redis

