apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: webservice

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: webservice

    spec: 
      containers:
        - name: nginx-container
          image: nginx

  replicas: 6
  selector:
    matchLabels:
      type: webservice
