apiVersion: v1
kind: Pod
metadata:
  name: interactive-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 30; done"]
      tty: true
      stdin: true

