Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false

  # Minimal setup - just ensure the script is available
  $minimal_setup = <<-SCRIPT
    # Make kube-install.sh executable if it exists
    if [ -f /vagrant/kube-install.sh ]; then
      chmod +x /vagrant/kube-install.sh
    fi
  SCRIPT

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    master.vm.provision "shell", inline: $minimal_setup
  end

  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    worker.vm.provision "shell", inline: $minimal_setup
  end

  config.vm.define "worker2" do |worker|
   worker.vm.hostname = "worker2"
   worker.vm.network "private_network", ip: "192.168.56.12"
   worker.vm.provider "virtualbox" do |v|
     v.memory = 2048
     v.cpus = 2
   end
   worker.vm.provision "shell", inline: $minimal_setup
  end
end
