apiVersion: v1
kind: PersistentVolume
metadata:
  name: story-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /story
    type: DirectoryOrCreate
